name: GitHub Actions Self-hosted Demo
on:
  workflow_dispatch:
      inputs:
        tag:
          required: true
          type: string
          description: Version tag of the release

jobs:
  show-runner:
    uses: ./.github/workflows/reusable.yml
    with:
      tag: ${{ inputs.tag }}
      runs-on: local
  show-runner-again:
    runs-on: ubuntu-latest
    needs: show-runner
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Re-use workflow
          uses: https://github.com/desombre/gh-actions-demo/blob/master/.github/workflows/reusable.yml@master
          with:
            tag: ${{ inputs.tag }}
            runs-on: ubuntu-latest

